計算したsha1ハッシュをメモリ上に保存
AzisabaNetwork/YukiTexture pull request #5
Opened 2021-06-04 18:17 UTC by acrylic-style

<details>
<summary>
変更点とか仕様とか
</summary>

- 未テスト
- /reloadtexで保存されたsha1ハッシュをリセット(リソパ更新を強制する)
- 未テスト
- Kotlinのバージョンを`1.4.10`→`1.5.10`に更新
- sha1ハッシュがすでに計算されてる場合はダウンロードしないでクライアントにURLとsha1ハッシュをそのまま投げる
- 未テストだって言ってるでしょ！！！
</details>

眠いのであとでテストする(と思う)

2021-06-05 05:02 UTC, acrylic-style commented
@Mori01231 review

2021-06-05 14:26 UTC, sya-ri requested changes

2021-06-05 14:26 UTC, sya-ri commented on src/main/kotlin/net/azisaba/yukitexture/YukiTexture.kt
> +                        .joinToString("\n"))
`map {}.joinToString()` は `joinToString {}` と書くべきであり、それをSuppressするのは良くありません。Suppress するくらいなら変更してください。

2021-06-05 14:26 UTC, sya-ri commented on src/main/kotlin/net/azisaba/yukitexture/YukiTexture.kt
> +            sha1 = DigestUtils.sha1Hex(result.get())
「SHA-1 を計算しました」というメッセージはこちらに入れるべきではないでしょうか？

2021-06-05 14:46 UTC, acrylic-style commented on src/main/kotlin/net/azisaba/yukitexture/YukiTexture.kt
> +                        .joinToString("\n"))
![image](https://user-images.githubusercontent.com/19150229/120895522-4612f000-c658-11eb-8aaf-04e70128789e.png)

2021-06-05 15:02 UTC, sya-ri approved these changes

2021-06-07 07:07 UTC, sya-ri commented
あくまでハッシュのメモリキャッシュなので、変更を加えるなら別のPRにするべきだと思います。

また、

 > 20 にしたとおもってた

というコミットするくらいなら --amend してください

2021-06-07 07:34 UTC, acrylic-style commented
1) そもそも最初からmasterブランチからPRしたこと/依頼を受けたときの私の解釈が間違っていた

2) force push回避 (一度pushしたあとに修正したので)

どちらもすでにcloneしてる人が影響を受けるので今は変えません

2022-11-16 04:30 UTC, closed without merging